[package]
name = "syntax_visualizer"
version = "0.1.0"
authors = ["gentoo90 <gentoo90@gmail.com>"]

[dependencies]
error-chain = "0.11"
glib-sys = "0.4"
gtk-sys = "0.4"
glib = "0.3.1"
gtk = { version = "0.2", features = ["v3_10"] }
sourceview = "0.2"
syntex_syntax = "0.59"
syntex_pos = "0.59"
